# Generated by Django 4.2 on 2025-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_acceptednft_acceptedtoken_listing_loan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.IntegerField(choices=[(1, "OPEN"), (2, "CLOSED")], default=1),
        ),
    ]
